name: Build and Deploy

on:
  push:
    branches: [ "example" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --force

    - name: Build project
      run: npm run next-build && npm run export
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Deploy files to Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        protocol: ftp
        local-dir: ./out/
        server-dir: /www/example.it43.space/
