name: Build and Deploy

on:
  push:
    branches: [ "example" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Clear cache and remove folders
      run: |
        rm -rf node_modules
        rm -rf .next
        npm cache clean --force

    - name: Install dependencies
      run: npm ci --force

    - name: Build project
      run: npm run next-build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Deploy files to Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        protocol: ftp
        local-dir: ./out/
        server-dir: /www/example.it43.space/
        dangerous-clean-slate: true